buildscript {
    repositories {
        maven{url "https://maven.aliyun.com/repository/gradle-plugin"}
        maven{url "https://maven.aliyun.com/repository/public"}
        maven{url "https://maven.aliyun.com/repository/central"}
        mavenCentral()
        google()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.3.2'
    }
}

allprojects {
    repositories {
        maven{url "https://maven.aliyun.com/repository/public"}
        maven{url "https://maven.aliyun.com/repository/central"}
        mavenCentral()
        google()
    }
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}